CREATE TABLE IF NOT EXISTS CATEGORIES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- カテゴリID
  NAME TEXT NOT NULL UNIQUE, -- カテゴリ名
  NAME_EN TEXT NOT NULL UNIQUE -- カテゴリ名アルファベット表記
);

CREATE TABLE IF NOT EXISTS TAGS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- タグID
  NAME TEXT NOT NULL UNIQUE, -- タグ名
  NAME_EN TEXT NOT NULL UNIQUE -- タグ名アルファベット表記
);

CREATE TABLE IF NOT EXISTS POSTS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 記事のID
  CATEGORY_ID INTEGER NOT NULL,  -- カテゴリID
  TITLE TEXT NOT NULL, -- 記事のタイトル
  SLUG TEXT NOT NULL UNIQUE, -- URLに使用するslug(/category名/idとなるようにする※この値も使用してmarkdownも保存する)
  MAIN_TEXT TEXT NOT NULL, -- 本文の一部（50byte制限※記事一覧の見出しの一部に使用）
  STATUS TEXT NOT NULL, -- 記事ステータス（draft:下書き, released:投稿済み, withdrawn: 取り下げ）
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, -- レコード作成日
  UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, -- レコード更新日
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) -- カテゴリIDの外部キー制約
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
  POST_ID INTEGER NOT NULL, -- 記事ID
  TAG_ID INTEGER NOT NULL, -- タグID
  FOREIGN KEY (POST_ID) REFERENCES POSTS(ID), -- 記事IDの外部キー制約
  FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID), -- タグIDの外部キー制約
  PRIMARY KEY (POST_ID, TAG_ID) -- 複合主キー制約
);

CREATE TABLE ADMIN_USERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- ID
  USERNAME TEXT NOT NULL UNIQUE, -- ユーザー名
  PASSWORD_HASH TEXT NOT NULL -- パスワード（ハッシュ値）
);

CREATE TABLE ACCESS_LOGS_DAILY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主キー
  POST_ID INTEGER NOT NULL, -- 記事ID
  USER_AGENT TEXT, -- エージェント名
  IP_ADDRESS TEXT, -- APアドレス
  ACCESSED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- アクセス日時
);

CREATE TABLE ACCESS_TOTALS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主キー
  POST_ID INTEGER NOT NULL, -- 記事ID
  ACCESS_DATE TEXT NOT NULL, -- 日付(YYYY-MM-DD形式)
  ACCESS_COUNT INTEGER NOT NULL, -- アクセス数
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, -- レコード作成日
  UNIQUE(POST_ID, ACCESS_DATE)
);

CREATE TABLE REVOKED_TOKENS (
  TOKEN TEXT NOT NULL, -- TOKEN
  REVOKED_AT DATETIME DEFAULT CURRENT_TIMESTAMP -- 失効日時カラム
);